#index:
#    path: /
#    controller: App\Controller\DefaultController::index
base:
  path: /base
  controller: App\Controller\LuckyController::base

home:
  path: /home
  controller: App\Controller\LuckyController:home

name:
  path: /name/{name}
  controller: App\Controller\LuckyController:name